GET http://localhost:3000/api/translate/en/aku cinta kamu

###
GET http://localhost:3000/api/news/top-headlines?q=football&translateTo=id

###
GET http://localhost:3000/api/news/everything?q=google&translateTo=id

###
<script src='//vws.responsivevoice.com/v/e?key=LCM0tsDc'></script>

